### PR TITLE
add in ComputerCraft support back in, WIP

### PR DESCRIPTION
**Pull request by binary1230**
stubs out original functionality, still needs a little more work to complete but is mostly there.

This is nearly completed, working OK.  probably could break this up into a couple PR's, let me know if you'd like this.

I'd be interested in hearing your opinion on the Gradle changes here, which I had to play around with significantly to figure out how to make this work.  I ended up decompiling the older webdisplays mod and put some of the original code back in here.

- Add back in computercraft/modem/cable support
- Use only API classes from MCEF (some stray logging was present which skipped the API)

before merging:
- [ ] write some docs on how to setup the dev environment, it took forever to figure out the correct gradle settings for OpenComputers and ComputerCraft API jars
- [x] finish TileEntityCCInterface::callMethod(), has a few more things to flesh out there
- [ ] test saving/loading and server-based play
- [ ] ensure works with older 0.9 MCEF (I was testing with my new beta 0.10 version which has open PRs)
- [ ] cleanup unused import statements

fixes https://github.com/montoyo/webdisplays/issues/7

### CODE REVIEW

**Comment by binary1230** [comment]
image

**Comment by wifiblog** [comment]
hello, I try to operate this interface as in the photo, except I can not, he said that computercraft are not installed when it is functional on his side.

**Comment by binary1230** [comment]
Hey @wifiblog, this support doesn't work in the currently released version of WebDisplays

You are leaving a comment on requested changes to the code which would reenable computercraft, but the original author would have to take action to merge these changes in.

So for now, it won't work.  I have been trying to get in touch with the original author for a few weeks, if I can't, i might clean this up some more and release an unofficial version of WebDisplays soon

**Comment by wifiblog** [comment]
Thank you for your answer, I would be very interested in this feature.

I hope you will get in touch with him.

**Pull request closed without merging**
